require 'ipfs-http-client-rb/commands/base'
require 'ipfs-http-client-rb/commands/ls'
require 'ipfs-http-client-rb/commands/cat'
require 'ipfs-http-client-rb/commands/cat_to_file'
require 'ipfs-http-client-rb/commands/add'
require 'ipfs-http-client-rb/commands/add_dir'
require 'ipfs-http-client-rb/commands/pin_rm'
require 'ipfs-http-client-rb/commands/pin_add'
